version: '3.8'

services:
  # Container backend (NestJS)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    env_file:
      - ./src/backend/.env
    ports:
      - "3000:3000"

  # Container frontend (React)
  #frontend:
  #  build:
  #    context: ./src/frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "5173:80"